### ISSUE TITLE
[Windows 8 & 10] The context menu needs restarting explorer to appear on update from the old NppShell_06.dll to new NppShell.dll

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/nppShell#13]
Under Windows 8 & Windows 10, the context menu needs restarting explorer to appear, after updating from the old NppShell_06.dll to new NppShell.dll.

**Comment by donho** [comment]
@GurliGebis 
Could you review this PR?

Also here's the newest packages TEST11:
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST11/

**Comment by GurliGebis** [comment]
@donho if we use #15, they will be scheduled for deletion on next restart.
It should leave the current setup fine, so the cleanup will finish the next time the user restarts.
