### ISSUE TITLE
v 8.5.3 x64 - Explorer context menu accelerator key ('N') not active

### ISSUE THREAD

**Issue by eelco1** [notepad-plus-plus/nppShell#33]
Hi,

Not a bug perse, but I think that due to the new translatable "Edit with Notepad++" menu item, I can no longer open Explorer's context menu and use the 'N' key to quickly open NP++ (or any other keystroke).
The Title value in the CLSID's Settings registry key still shows "Edit with &Notepad++", but I suppose the menu text now comes from the dll.
I run W10 in US-en language.

Kind regards,

Eelco Ligtvoet.

**Comment by Susko3** [comment]
Same problem on Windows 11. Since the accelerator key is the main way I use Notepad++, I decided to hack it in myself: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13678#issuecomment-1616801041.

**Comment by GurliGebis** [comment]
It is possible to add back to the old/classic menu - I have asked @donho about it in the thread you are linking to.
The new menu doesn't support it, so there isn't much we can do there.

**Comment by GurliGebis** [comment]
@donho since it is included in the translations now, that works for the old menu - can you close this issue, since it is solved to the best of our abilities?
