### ISSUE TITLE
Right click and selecting "Edit with Notepad++" causes Explorer.exe to crash when using Windows 11 Safe Mode

### ISSUE THREAD

**Issue by mkupper** [notepad-plus-plus/nppShell#45]
### Description of the Issue
Please see [this Notepad++ forum thread](https://community.notepad-plus-plus.org/topic/24974/notepad-installation-and-explorer-exe-crash-only-in-safe-mode) for screen shots for how the issue was reported and reproduced. While the OP mentioned Notepad__ v8.5.7 it is not confirmed if this also happens with older versions of Notepad++.

Additional note from [xomx](https://github.com/xomx) on the previous [npp issue 14194](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14194) thread:
> NppShell.dll v1.2

### Steps to Reproduce the Issue

1.  Boot Windows 11 in Safe Mode
2. From Windows Explorer do right click and then "Edit with Notepad++" on a .txt file
3. Explorer will crash and restart.

### Expected Behavior
Open Notepad++ for the selected file.

### Debug Information
People reporting and reproducing the issue are shy and have not posted debug info other than "N++ v8.5.7 x64."

**Comment by imanubdesigner** [comment]
I add (indeed, I correct one thing): as soon as the right mouse button is clicked on any application, image (I had only tried these two types of files), explorer.exe **crashes before being able to display the contextual menu** (consequently, I can't even see a "Edit with Notepad++"). Thank you!

**Comment by donho** [comment]
@mkupper & @imanubdesigner 
The new installers which contain the fix of crash in Safe Mode is available here for testing:
http://download.notepad-plus-plus.org/repository/MISC/fixSafeModeCrash/

The binaries are signed. Could you test the binary of your choice and confirm if the crash has been fixed please?

**Comment by imanubdesigner** [comment]
I just got hold of the computer. Sorry for any delay. Yes, I confirm that the explorer.exe crash problem (a brutal refresh just after clicking the right mouse button) has been resolved. Now, when you right click, there is the usual Windows context menu. 

Thank you!

**Comment by mkupper** [comment]
Thank you @xomx and @donho I was also able to confirm that the old npp 8.5.7 (both x32 and x64) crashes Explorer when in Windows 11 Safe Mode and that both of the new npp 8.5.7 with the nppShell fix work in Windows 11 Safe mode and also seem fine in Windows 11 standard mode. I did not test the ARM version.

The crash with the old version was interesting in that when you right clicked on a file then Explorer.exe would quietly vanish instead of showing the right-click context menu.
