### ISSUE TITLE
[Win11] Edit With Notepad++ shown with video files

### ISSUE THREAD

**Issue by Hadden89** [notepad-plus-plus/nppShell#48]
Probably a win issue, but Is a bit fun to be able to edit video files with notepad++ :D 

![image](https://github.com/notepad-plus-plus/nppShell/assets/18642541/5fe5a17f-988a-4424-b0aa-e15671085469)

Npp 8.5.7
Win11 22H2 22621.2361

**Comment by GurliGebis** [comment]
The problem is that there is no denylist for filetypes in the msix manifest. 
So we would have to implement it in code.

@donho what do you think? Should I add change the code, so if certain media files (images, audio and video) is right clicked, we just return false to showing the menu item?

**Comment by donho** [comment]
@GurliGebis 
Some users (if not a lot of user) want to modify everything with Notepad++, so let's keep this "feature" :)

**Comment by GurliGebis** [comment]
@donho If they can modify those kinds of files in notepad++, I'll say, all the power to them 😀
